### ISSUE TITLE
Malformed extended header: missing newline

### ISSUE THREAD

**Issue by verchol** [mafintosh/tar-fs#21] opened 2015-08-18 07:58 UTC
Hi,

when trying to open (with another tar utility, such as gnu tar or docker) very large (1 GB+) tar files generated with tar-fs, one gets errors such as:
- Malformed extended header: missing newline
- Untar re-exec error: archive/tar: invalid tar header: output: 

FYI

**Comment by mafintosh** [comment] 2015-08-18 08:06
Can you create a script that reprodcues this?

**Comment by verchol** [comment] 2015-08-18 08:56
actually, apparently, surprisingly - no.
still get the error on the original folder, but just generating a few really heavy files doesn't reproduce it.
maybe it's something else about the folder - number of files, nesting depth...
will investigate.

**Comment by verchol** [comment] 2015-08-18 10:18
hmm, the issue might be broken symlinks while not using the dereference option. investigating.

**Comment by verchol** [comment] 2015-08-18 15:09
forget earlier comments. possibly related to pax headers. still working on it.

**Comment by christianhuening** [comment] 2015-08-24 16:40
Having the same issue. I pack basically four types of files in my exmaple:
1. A 240 MB GIS file in the ASC format. this basically is a file containing strings in a grid, depicting the elevation map of an area
2. a Dockerfile file
3. DLLs compiled via Mono from C# sources

That's it. I have no clue what PAX headers are however? Anywhay, with a similar setup of files it worked the other day.

**Comment by mikeifomin** [comment] 2015-08-27 10:19
I have the same problem on my MacOS when deploying MateorJS application [https://github.com/arunoda/meteor-up]
So i think problem with tar executable.

**Comment by christianhuening** [comment] 2015-08-27 10:25
Yeah update here: The problem definitely is not related to the files I have in my archive. We now use a work-around which involves a system call to the underlying ubuntu's tar command. this is safe for now, since we're using a docker image an can rely on that. But it's not cool :(

**Comment by mikeifomin** [comment] 2015-09-04 11:56
So i found problem for me. There was an cyrillic named file in subdirectory :)  
Now "it works"!

**Comment by mikeifomin** [comment] 2015-09-04 15:15
@mafintosh I'll try in a few days.

**Comment by mikeifomin** [comment] 2015-09-04 19:35
Today I dig deeper and it seems an error appears in some "magic" directory structure. 

error appears
```
bundle/programs/server/npm/webapp/node_modules/connect/lib/public/Без названия-3
```


error NOT appears (without last char)
```
bundle/programs/server/npm/webapp/node_modules/connect/lib/public/Без названия-
```

The same problem when using  [node-archiver](https://github.com/archiverjs/node-archiver)

I wrote test that fails. Need pull request with it?

**Comment by reidbarber** [comment] 2016-05-12 22:19
Did you ever solve this issue? I am having the same problem on mupx deploy

**Comment by mikeifomin** [comment] 2016-05-12 23:46
@reidbarber I just deleted file with this problem. So maybe you have some assets with non-latin alphabet symbols. Try to remove them.

**Comment by reidbarber** [comment] 2016-05-13 00:10
Ok, thanks for the reply! I'll keep digging through the hierarchy.

**Comment by alexpriceonline** [comment] 2017-10-19 08:01
I'm having the same issue with my `mup` deploy. Any way I can debug/fix?

**Comment by reidbarber** [comment] 2017-10-19 15:49
You likely have a non-ascii character in a filename. Try to manually look through and find one or maybe you can write a script if you have too many files to sort through.

**Comment by pptoan23** [comment] 2017-11-01 04:31
@alexpriceonline I have the same issue. Did you have a solution yet?

**Comment by alexpriceonline** [comment] 2017-11-01 09:42
@pptoan23 I'm sure it was an issue with one of the packages like the above comments suggested, but I couldn't work it out. I switched to using [pm2-meteor](https://github.com/andruschka/pm2-meteor) and that worked great!

**Comment by ddaydd** [comment] 2017-11-02 08:42
Hi,
Same error, I did not find a file with a weird name, pm2 does not work for me under windows ,no other solution?
@alexpriceonline are not you under windows?
I thought the mistake was for those who was under windows

**Comment by alexpriceonline** [comment] 2017-11-02 08:43
I'm on MacOS 10.13

**Comment by zodern** [comment] 2017-11-02 12:54
@alexpriceonline I wasn't able to reproduce using your reproduction. It might help seeing the bundle created by meteor and the tar file. If you run `mup deploy --cached-build`, it shows you where they are at. You could then copy them into a `.build` folder in your reproduction and push them to github.

**Comment by alexpriceonline** [comment] 2017-11-05 10:29
@zodern is this now fixed with `1.3.5`? I dont have time to test with my prod app right now.

**Comment by zodern** [comment] 2017-11-05 14:44
@alexpriceonline Yes

**Comment by alexpriceonline** [comment] 2017-11-05 15:48
Close the issue? :)

**Closed** 2017-11-05 15:52 UTC
